#!/usr/bin/env bash
# Send a file to my server with scp
function error_message {
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

if [ "$#" -lt 4 ]; then
    error_message
else
    scp -i "$4" -o "StrictHostKeyChecking=no" "$1" "$3@$2:~/"
fi
