#!/usr/bin/env bash
# Send a file to my server with scp
function error_message {
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
}

if [ $# -lt 3 ]; then
    error_message
else
    scp -o 'StrictHostKeyChecking no' -i "$4" "$1" "$3@$2:~/"
fi
