#!/usr/bin/env bash
# confirgure the redirection of Nginx
sudo -y apt-get update
sudo -y apt-get install nginx
sed -i '46 i \\trewrite ^/redirect_me http://www.cristiandiaz.com permanent;' /etc/nginx/sites-available/default
service nginx restart
