#!/usr/bin/env bash
# confirgure the redirection of Nginx
apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default
service nginx start
