#!/usr/bin/env bash
# config two servers
apt-get update
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
new="server_name _;\n\trewrite ^\/redirect_me youtube.com permanent;"
hst="\n\tadd_header X-Served-By \$hostname;"
er="\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sed -i "s/server_name _;/$new$hst$er/" /etc/nginx/sites-enabled/default
service nginx restart
