#!/usr/bin/env bash
# config to server HAproxy
apt-get update -y
apt-get install haproxy -y
echo "frontend holbnbclone
                 bind *:80
                 default_backend servers
" >> /etc/haproxy/haproxy.cfg

echo "backend servers
                balance roundrobin
                server 1185-web-01 35.227.39.47
                server 1185-web_02 34.74.164.192
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
