#!/usr/bin/env bash
# Dump in .tgz and .sql files
dia="$(date +%d)"
mes="$(date +%m)"
year="$(date +%Y)"
mysqldump -u root -p "$2" --all-databases --opt > backup.sql
tar -czvf "$dia-$mes-$year.tar.gz" backup.sql

