#!/usr/bin/env bash
# create a file.pid, while, and handle Signalsm
path="/var/run/holbertonscript.pid"
echo "$$" > $path
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm $path' SIGQUIT || SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
