#!/usr/bin/env bash
# FizzBuzz sequence.
num=1
while [ $num -le 100 ]
do
    if ((num % 3 == 0)) && ((num % 5 == 0))
    then
       echo "FizzBuzz"
    elif ((num % 5 == 0))
    then
	echo "Buzz"
    elif ((num % 5 == 0))
    then
	echo "Fizz"
    else
	echo "$num"
    fi
    ((num++))
done
