#!/usr/bin/env bash
# print 1-20 num, with case for numbers 4, 9, 17
x=1
while [ $x -lt 21 ]
do
    echo "$x"
    case "$x" in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((x++))
done
