#!/usr/bin/env bash
# change the host localhost and facebook
cp /etc/hosts ~/hosts.new
check_local=$(grep -n "127.0.0.2 localhost" ~/hosts.new | cut -d ":" -f2)
str=$(grep -n "127.0.0.1" ~/hosts.new)
check_fb=$(grep -n "8.8.8.8 facebook.com" ~/hosts.new | cut -d ":" -f2)
host_fb="8.8.8.8 facebook.com"
if [ -z "$check_local" ]; then
    if [ -n "$str" ]; then
        sed 's/127.0.0.1/127.0.0.2/' /etc/hosts > ~/hosts.new
    fi
fi
if [ -z "$check_fb" ]; then
    echo "$host_fb" >> ~/hosts.new
fi
cp -f ~/hosts.new /etc/hosts
