#!/usr/bin/env bash
# How to run proceswith nginx user
sudo chmod a+rwx /etc/nginx/nginx.config
sudo killall apache2
sudo sed -i "s/89/8080/" /etc/nginx/sites-enabled/default
sudo -u nginx services nginx start
