#!/usr/bin/env bash
# How to run proceswith nginx user
sudo chmod a+rwx /etc/nginx/nginx.conf
sudo killall apache2
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
